# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsbuffer',
            old_name='type',
            new_name='level',
        ),
    ]
