# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 14:04
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logging', '0002_auto_20180321_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsbuffer',
            name='log',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
